[package]
name = "dal"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.refinery]
version = "0.8.4"
default-features = false
features = ["mysql"]

[dependencies.mysql]
version = "=22.0.0"
default-features = false
features = ["rustls-tls"]